name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  compile:
    name: dart compile exe
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            binary-name: fl_freezed_brick_linux_amd64
          - runs-on: macos-latest
            binary-name: fl_freezed_brick_macos_amd64
          - runs-on: windows-latest
            binary-name: fl_freezed_brick_windows.exe
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - run: cd bricks/fl_freezed_brick/hooks && dart pub get
      - run: cd bricks/fl_freezed_brick/hooks && mkdir ${{ matrix.runs-on }}
      - run: cd bricks/fl_freezed_brick/hooks && dart compile exe app.dart -o ${{ matrix.runs-on }}/${{ matrix.binary-name }}
      - uses: actions/upload-artifact@v2
        with:
          name: bin-${{ matrix.runs-on }}
          path: bricks/fl_freezed_brick/hooks/${{ matrix.runs-on }}

  release:
    needs: compile
    name: github release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bin-ubuntu-latest
          path: bin-linux
      - uses: actions/download-artifact@v2
        with:
          name: bin-macos-latest
          path: bin-macos
      - uses: actions/download-artifact@v2
        with:
          name: bin-windows-latest
          path: bin-windows
      # - uses: softprops/action-gh-release@v1
      #   with:
      #     draft: true
      #     files: bin-*/*
